name: Drivers (Windows ARM64) (Wake Up)
description: Wake Up issues with Windows ARM64 Drivers
labels: [Drivers, Windows ARM64, Wake Up]
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '....'
        2. Click on '....'
        3. Scroll down to '....'
        4. See the error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Pictures/Screenshots
      description: If applicable, add pictures to help explain your problem.
    validations:
      required: true
  - type: input
    attributes:
      label: UEFI Version
      description: The version of the UEFI being used, or commit hash
      placeholder: e.g. 2.12
    validations:
      required: true
  - type: input
    attributes:
      label: Operating System
      description: Operating System being booted
      placeholder: e.g. Windows 11 Professional ARM64 build 22000.160
    validations:
      required: true
  - type: input
    attributes:
      label: BootShim
      description: Version of Bootshim being used to load the UEFI
      placeholder: e.g. 174 (Latest)
    validations:
      required: true
  - type: input
    attributes:
      label: Device
      placeholder: e.g. Lumia 950 XL Single SIM (RM-1085)
    validations:
      required: true
  - type: input
    attributes:
      label: Stock Firmware
      description: check about in Windows Phone or your stock FFU file, or WPinternals
      placeholder: e.g. 1078.0053
    validations:
      required: true
  - type: input
    attributes:
      label: Battery Vendor
      description: pull your battery out
      placeholder: e.g. Microsoft Mobile
    validations:
      required: true
  - type: input
    attributes:
      label: Battery Manufacturing Date
      description: pull your battery out
      placeholder: e.g. 11/2015
    validations:
      required: true
  - type: input
    attributes:
      label: Hardware Version
      description: check about in Windows Phone or the Advanced Info application in WOA
      placeholder: e.g. 1.0.0.2
    validations:
      required: true
  - type: input
    attributes:
      label: Type of deployment
      description: What you used for deploying
      placeholder: e.g. WOA Deployer or FFU (thor2)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant Assets
      description: |
        A list of assets (logs, pictures or other details) relevant to this bug.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: |
        To upload the log
          - Open WOA Deployer, go to the advanced tab, and click "collect logs". Come back here, and attach the file.
