name: Drivers (Windows ARM64) (TPM)
description: TPM issues with Windows ARM64 Drivers
labels: [Drivers, Windows ARM64, TPM]
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '....'
        2. Click on '....'
        3. Scroll down to '....'
        4. See the error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Pictures/Screenshots
      description: If applicable, add pictures to help explain your problem.
    validations:
      required: true
  - type: dropdown
    id: uefi-version
    attributes:
      label: What version of the UEFI are you currently running?
      description: |
        - You can find out what version of the UEFI you are running by going to the Advanced Info application on WOA.
        - **Windows 11**: Settings ➡️ Devices and Printers ➡️ Bluetooth ➡️ View lumia specific information
        - **Windows 10/10X**: Settings ➡️ Devices ➡️ Bluetooth and other devices ➡️ View lumia specific information

        Then read the Core Version field with "EDK2" marked in it.

        - You also can find this information when the phone boots up on the screen of the phone.
      multiple: false
      options:
        - '2.22'
        - '2.21-c'
        - '2.21-b'
        - '2.21'
        - '2.20'
        - '2.11.0'
        - '2.10.0'
        - '2.0.7'
        - '2.0.6'
        - '2.0.5'
        - '2.0.4'
        - '2.0.3'
        - '2.0.2'
        - '2.0.1'
        - '2.0.0'
        - '1.20'
        - '1.09'
        - '0.1.1'
        - '0.1'
        - 'Other (please specify below)'
    validations:
      required: true
  - type: input
    attributes:
      label: UEFI Version (if not specified above)
      description: The version of the UEFI being used, or commit hash
      placeholder: e.g. 2.12
    validations:
      required: false
  - type: dropdown
    id: bsp-version
    attributes:
      label: What version of the BSP are you currently running?
      description: |
        - You can find out what version of the BSP you are running by going to the Advanced Info application on WOA.
        - **Windows 11**: Settings ➡️ Devices and Printers ➡️ Bluetooth ➡️ View lumia specific information
        - **Windows 10/10X**: Settings ➡️ Devices ➡️ Bluetooth and other devices ➡️ View lumia specific information

        Then read the release information field.
      multiple: false
      options:
        - 'v2108.58 (Prussian Blue)'
        - 'v2108.44 (Prussian Blue)'
        - 'v2108.42 (Prussian Blue)'
        - 'v2107.12'
        - 'v2105.22'
        - 'v2105.1'
        - 'v2103.32'
        - 'v2103.6'
        - 'v2102.75'
        - 'v2102.71'
        - 'v2102.60'
        - 'v2102.21'
        - 'v2102.14'
        - 'v2102.1'
        - '2012.1'
        - '2012'
        - '2011'
        - '2009.63'
        - '2009'
        - '2006'
        - '2005'
        - '2003.2.2'
        - '2003.2'
        - '2003.1'
        - '2003'
        - 'Other (please specify below)'
    validations:
      required: true
  - type: input
    attributes:
      label: BSP Version (if not specified above)
      description: The version of the BSP being used, or commit hash
      placeholder: e.g. v2108.58
    validations:
      required: false
  - type: input
    attributes:
      label: Operating System
      description: Operating System being booted
      placeholder: e.g. Windows 11 Professional ARM64 build 22000.160
    validations:
      required: true
  - type: input
    attributes:
      label: BootShim
      description: Version of Bootshim being used to load the UEFI
      placeholder: e.g. 174 (Latest)
    validations:
      required: true
  - type: input
    attributes:
      label: Device
      placeholder: e.g. Lumia 950 XL Single SIM (RM-1085)
    validations:
      required: true
  - type: input
    attributes:
      label: Stock Firmware
      description: check about in Windows Phone or your stock FFU file, or WPinternals
      placeholder: e.g. 1078.0053
    validations:
      required: true
  - type: input
    attributes:
      label: Battery Vendor
      description: pull your battery out
      placeholder: e.g. Microsoft Mobile
    validations:
      required: true
  - type: input
    attributes:
      label: Battery Manufacturing Date
      description: pull your battery out
      placeholder: e.g. 11/2015
    validations:
      required: true
  - type: input
    attributes:
      label: Hardware Version
      description: check about in Windows Phone or the Advanced Info application in WOA
      placeholder: e.g. 1.0.0.2
    validations:
      required: true
  - type: dropdown
    id: deployment-type
    attributes:
      label: Select any case that applies to your deployment
      multiple: false
      options:
        - 'I have deployed Windows using WOA Deployer and never updated using the Driver Updater utility'
        - 'I have deployed Windows using WOA Deployer and updated using the Driver Updater utility afterwards'
        - 'I have deployed Windows using a custom FFU file using THOR2 and never using the Driver Updater utility'
        - 'I have deployed Windows using a custom FFU file using THOR2 and updated using the Driver Updater utility afterwards'
        - 'I have deployed Windows manually myself and never updated using the Driver Updater utility'
        - 'I have deployed Windows manually myself and updated using the Driver Updater utility afterwards'
    validations:
      required: true
  - type: input
    attributes:
      label: Type of deployment
      description: What you used for deploying
      placeholder: e.g. WOA Deployer or FFU (thor2)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant Assets
      description: |
        A list of assets (logs, pictures or other details) relevant to this bug.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: |
        To upload the log
          - Open WOA Deployer, go to the advanced tab, and click "collect logs". Come back here, and attach the file.
